# EMOTION ANALYSIS 

# Data Preprocessing and Cleaning

In [2]:
import re
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import string
import nltk
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
%matplotlib inline

In [3]:
import pandas as pd 
train  = pd.read_csv('C:/Users/Irfan/PycharmProjects/HateSpeechAnalysis/emotion analysis MM/kaggletrain.csv')
test = pd.read_csv('C:/Users/Irfan/PycharmProjects/HateSpeechAnalysis/emotion analysis MM/kaggletest.csv')
print len(train)
train.head()
train.count()

5970


Id          5970
Category    5970
Tweet       5970
dtype: int64

In [4]:
combi = train.append(test, ignore_index=True)
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i,'', input_txt)
        
    return input_txt

# remove the duplicate tweet

In [5]:
train=train[~train['Tweet'].duplicated()]
train=train.reset_index(drop=True)
print len(train)
print train.Tweet[1]
train.head()

5418
IOS 9 App Transport Security. Mm need to check if my 3rd party network pod supports it http://t.co/fmtcfUAdgj


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Id</th>
      <th>Category</th>
      <th>Tweet</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>635769805279248384</td>
      <td>negative</td>
      <td>Not Available</td>
    </tr>
    <tr>
      <th>1</th>
      <td>635930169241374720</td>
      <td>neutral</td>
      <td>IOS 9 App Transport Security. Mm need to check...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>635950258682523648</td>
      <td>neutral</td>
      <td>Mar if you have an iOS device, you should down...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>636030803433009153</td>
      <td>negative</td>
      <td>@jimmie_vanagon my phone does not run on lates...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>636100906224848896</td>
      <td>positive</td>
      <td>Not sure how to start your publication on iOS?...</td>
    </tr>
  </tbody>
</table>
</div>

# convert data to lowercase

In [7]:
import string
for i in range(len(train)):
    text = string.lower(train['Tweet'].iloc[i])
    train['Tweet'].iloc[i]=text
print train['Tweet'][2]
train.head()

mar if you have an ios device, you should download our app too: http://t.co/gl3tn2udnd


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Id</th>
      <th>Category</th>
      <th>Tweet</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>635769805279248384</td>
      <td>negative</td>
      <td>not available</td>
    </tr>
    <tr>
      <th>1</th>
      <td>635930169241374720</td>
      <td>neutral</td>
      <td>ios 9 app transport security. mm need to check...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>635950258682523648</td>
      <td>neutral</td>
      <td>mar if you have an ios device, you should down...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>636030803433009153</td>
      <td>negative</td>
      <td>@jimmie_vanagon my phone does not run on lates...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>636100906224848896</td>
      <td>positive</td>
      <td>not sure how to start your publication on ios?...</td>
    </tr>
  </tbody>
</table>
</div>

# remove RT and URL

In [9]:
pattern=r'rt @\w+: '     #remove RT
for i in range(len(train)):
    train['Tweet'].iloc[i] = re.sub(pattern,'',train['Tweet'].iloc[i], flags=re.MULTILINE)
    
                  #remove URL
pattern=r'\w+:\/{2}[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*'
for i in range(len(train)):
    train['Tweet'].iloc[i] = re.sub(pattern,'',train['Tweet'].iloc[i], flags=re.MULTILINE)
print train.Tweet[1]
train.head()   

ios 9 app transport security. mm need to check if my 3rd party network pod supports it 


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Id</th>
      <th>Category</th>
      <th>Tweet</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>635769805279248384</td>
      <td>negative</td>
      <td>not available</td>
    </tr>
    <tr>
      <th>1</th>
      <td>635930169241374720</td>
      <td>neutral</td>
      <td>ios 9 app transport security. mm need to check...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>635950258682523648</td>
      <td>neutral</td>
      <td>mar if you have an ios device, you should down...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>636030803433009153</td>
      <td>negative</td>
      <td>@jimmie_vanagon my phone does not run on lates...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>636100906224848896</td>
      <td>positive</td>
      <td>not sure how to start your publication on ios?...</td>
    </tr>
  </tbody>
</table>
</div>

# stop word removal

In [10]:
import string
import re
from nltk.corpus import stopwords
stopwords_english = stopwords.words('english')
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
from nltk.tokenize import TweetTokenizer

# remove number

In [11]:
import re
pattern=r'[0-9]+'
for i in range(len(train)):
    train['Tweet'].iloc[i] = re.sub(pattern,'',train['Tweet'].iloc[i], flags=re.MULTILINE)
print train['Tweet'][0]
train.head()

not available


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Id</th>
      <th>Category</th>
      <th>Tweet</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>635769805279248384</td>
      <td>negative</td>
      <td>not available</td>
    </tr>
    <tr>
      <th>1</th>
      <td>635930169241374720</td>
      <td>neutral</td>
      <td>ios  app transport security. mm need to check ...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>635950258682523648</td>
      <td>neutral</td>
      <td>mar if you have an ios device, you should down...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>636030803433009153</td>
      <td>negative</td>
      <td>@jimmie_vanagon my phone does not run on lates...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>636100906224848896</td>
      <td>positive</td>
      <td>not sure how to start your publication on ios?...</td>
    </tr>
  </tbody>
</table>
</div>

# Remove  (@) Handles

In [12]:
#remove @
pattern=r'@\w+ '
for i in range(len(train)):
    train['Tweet'].iloc[i] = re.sub(pattern,'',train['Tweet'].iloc[i], flags=re.MULTILINE)
train.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Id</th>
      <th>Category</th>
      <th>Tweet</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>635769805279248384</td>
      <td>negative</td>
      <td>not available</td>
    </tr>
    <tr>
      <th>1</th>
      <td>635930169241374720</td>
      <td>neutral</td>
      <td>ios  app transport security. mm need to check ...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>635950258682523648</td>
      <td>neutral</td>
      <td>mar if you have an ios device, you should down...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>636030803433009153</td>
      <td>negative</td>
      <td>my phone does not run on latest ios which may ...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>636100906224848896</td>
      <td>positive</td>
      <td>not sure how to start your publication on ios?...</td>
    </tr>
  </tbody>
</table>
</div>

# remove bad character

In [13]:
#[^A-Za-z ]
import re
pattern=r'[^A-Za-z ]'
for i in range(len(train)):
    train['Tweet'].iloc[i] = re.sub(pattern,'',train['Tweet'].iloc[i], flags=re.MULTILINE)
print train['Tweet'][1]
train.head()

ios  app transport security mm need to check if my rd party network pod supports it 


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Id</th>
      <th>Category</th>
      <th>Tweet</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>635769805279248384</td>
      <td>negative</td>
      <td>not available</td>
    </tr>
    <tr>
      <th>1</th>
      <td>635930169241374720</td>
      <td>neutral</td>
      <td>ios  app transport security mm need to check i...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>635950258682523648</td>
      <td>neutral</td>
      <td>mar if you have an ios device you should downl...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>636030803433009153</td>
      <td>negative</td>
      <td>my phone does not run on latest ios which may ...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>636100906224848896</td>
      <td>positive</td>
      <td>not sure how to start your publication on ios ...</td>
    </tr>
  </tbody>
</table>
</div>

# Remove Punctuations

In [14]:
# remove punctuation 
import string
string.punctuation
remove=string.punctuation
for i in range(len(train)):''
sent=train['Tweet'].iloc[i]
kd=' '.join(word.strip(remove) for word in sent.split())
train['Tweet'].iloc[i]=kd
print train.Tweet[0]
train.head()

# Tokenization

In [19]:
from textblob import TextBlob
import nltk
nltk.download('punkt')
TextBlob(train['Tweet'][1]).words     

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Irfan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


WordList(['ios', 'app', 'transport', 'security', 'mm', 'need', 'to', 'check', 'if', 'my', 'rd', 'party', 'network', 'pod', 'supports', 'it'])

# Stemming

In [20]:
from nltk.stem.porter import *
stemmer = PorterStemmer()
train = train.apply(lambda x: [stemmer.stem(i) for i in x]) # stemming
train.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Id</th>
      <th>Category</th>
      <th>Tweet</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>635769805279248384</td>
      <td>neg</td>
      <td>not avail</td>
    </tr>
    <tr>
      <th>1</th>
      <td>635930169241374720</td>
      <td>neutral</td>
      <td>ios  app transport security mm need to check i...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>635950258682523648</td>
      <td>neutral</td>
      <td>mar if you have an ios device you should downl...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>636030803433009153</td>
      <td>neg</td>
      <td>my phone does not run on latest ios which may ...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>636100906224848896</td>
      <td>posit</td>
      <td>not sure how to start your publication on ios ...</td>
    </tr>
  </tbody>
</table>
</div>

# A) Understanding the common words used in the tweets: WordCloud

In [21]:
all_words = ' '.join([text for text in train['Tweet']])
from wordcloud import WordCloud
wordcloud = WordCloud(width=800, height=500, random_state=21, max_font_size=110).generate(all_words)
plt.figure(figsize=(10, 7))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis('off')
plt.show()

In [22]:
# function to collect hashtags
def hashtag_extract(x):
    hashtags = []
    # Loop over the words in the tweet
    for i in x:
        ht = re.findall(r"#(\w+)", i)
        hashtags.append(ht)

    return hashtags

# Extracting Features from Cleaned Tweets

# Bag-of-Words Features

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
train_counts = count_vect.fit_transform(train.Tweet)
print train_counts.shape
count_vect.vocabulary_

(5418, 11990)


# TF-IDF Features

In [24]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
train_tfidf = tfidf_transformer.fit_transform(train_counts)
print train_tfidf.shape
print(tfidf_transformer.fit_transform(count_vect.fit_transform(train.Tweet)).toarray())

(5418, 11990)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
y_emotion =train['Tweet']